config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root "static_pages#home"
  get  "/help",      to: "static_pages#help"
  get  "/about",     to: "static_pages#about"
  get  "/contact",   to: "static_pages#contact"
  get  "/signup",    to: "users#new"
  get "/login",      to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update] 
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_nil: true

  # Returns the hash digest of the given string
  def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the DB for use in persistant sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end
  
  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def deactivate
    update_columns(activated: false, updated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private
    # Converts email to all lowercase.
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      # Create the token and digest.
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    if current_user.admin?
      @users = User.paginate(page: params[:page], :per_page => 10).order(params[:sort])
   else
      @users = User.where(activated:true).paginate(page: params[:page], :per_page => 10)
   end
  end 

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url
    else
      @user.errors.full_messages
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])
    if @user.update(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url, status: :see_other
      end
    end   

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end 
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  #returns the gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
    <%= form_with(model: @user) do |form| %>
      <%= render 'shared/error_messages' %>
      
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
      
      <%= form.label :email, "Email Address" %>
      <%= form.email_field :email, class: 'form-control' %>

      <%= form.label :password, "Password" %>
      <%= form.password_field :password, class: 'form-control' %>

      <%= form.label :password_confirmation, "Confirmation" %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>

      <%= form.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= gravatar_for user, size: 50 %></td>
  <td><%= link_to user.name, user %> </td>
  <td><%= user.updated_at.strftime('%m/%d/%Y') %></td>
  <td>Recipe submitted</td>
  <% if current_user.admin? %>
    <td>
      <% if user.activated? && !current_user?(user) %>
        <%= link_to "Deactivate", edit_account_activation_url(user.activation_token,
                                                    email: user.email, id: user.id, 
                                                    admin: true, deactivate: true) %>
       <% else %> 
        <% if !user.activated? %>
          <%= link_to "Activate", edit_account_activation_url(user.activation_token,
                                                    email: user.email, id: user.id, 
                                                    admin: true, activate: true) %>
        <% end %> 
      <% end %> 
    </td>
    <td>
      <% if !current_user?(user) %>
        <%= link_to "Del <i class='glyphicon glyphicon-trash'></i>".html_safe, 
            user, data: { "turbo-method": :delete,
                                            turbo_confirm: "You sure?"} %>
      <% else %> -
      <% end %>
    </td>
  <% end %>
  
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All users</h1>

<%= will_paginate %>
<table id="user_table">
    <tr>
      <th>Gravitar</th>
      <th><%= link_to "Name", :sort => "name"%></th>
      <th>Updated On</th>
      <th>Recipes</th>
      <% if current_user.admin? %>
        <th><%= link_to "Activated", :sort => "activated"%></th>
        <th>Delete</th>
      <% end %>
    </tr>

  <tbody>
  <%= render @users %>
  </tbody>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
footer bubble down below