config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root "static_pages#home"
  get  "/help",      to: "static_pages#help"
  get  "/about",     to: "static_pages#about"
  get  "/contact",   to: "static_pages#contact"
  get  "/signup",    to: "users#new"
  get "/login",      to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update] 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://worklifechaos.com/index.php/projects/">Recipe Book Project</a>
    by <a href="">Celeste Rance</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "recipe book", root_path, id: "logo" %>
        <nav>
          <div class="navbar-header">
            <button id="hamburger" type="button" class="navbar-toggle collapsed">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Github Project", "https://github.com/worklifechaos/recipe_book",
                    target: "_blank" %></li>
            <li><%= link_to "WLC", "https://worklifechaos.com/",
                    target: "_blank" %></li>
            
            <% if logged_in? %>
              <%# Links for logged-in users %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href ="#" id="account" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul id="dropdown-menu" class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete } %>
                    </li>
                </ul>
              </li>
            <% else %>
              <%# Links for non-logged-in-users %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>
     </div>
     <%= render 'layouts/footer' %> 
     <%= debug(params) if Rails.env.development? %> 
  </body>
</html>